### PR TITLE
Fix #76

### LINKED ISSUE #76: Need to map a column multiple times targeting multiple properties
It looks like only the last `mapper.AddMapping<ProductRow>("colname", p => p.propname1).SetPropertyUsing(blabla...)` is used.
It would be useful to allow 
```
mapper.AddMapping<ProductRow>("colname", p => p.propname1).SetPropertyUsing(blabla...)
mapper.AddMapping<ProductRow>("colname", p => p.propname2).SetPropertyUsing(blabla2...)
```

### PR DESCRIPTION
**Pull request by hguy**
Add a new ThenSetPropertyUsing() method in ColumnInfo in order to allow SetProp() chaining.

### CODE REVIEW

**Comment by mganss** [comment]
Thanks for creating this PR. To be honest, I don't like the approach of creating a separate mapping data structure that works only with `SetPropertyUsing()`. I'd prefer if we could actually have multiple mappings for a single column by having multiple values for the `ColumnsByName` and `ColumnsByIndex` dictionaries. Or is there a specific reason why you decided against this approach?

**Comment by hguy** [comment]
> 
> 
> Thanks for creating this PR. To be honest, I don't like the approach of creating a separate mapping data structure that works only with `SetPropertyUsing()`. I'd prefer if we could actually have multiple mappings for a single column by having multiple values for the `ColumnsByName` and `ColumnsByIndex` dictionaries. Or is there a specific reason why you decided against this approach?

I tried that first but there was a lot more impact on the codebase and in the current api (retro compatibility).
At some point you will have to specify what is the mapping in the collection that take care of the "Prop => Cell" and those that do the opposit. Currently the mapping passthrough the same ColumInfo for both.

_The need was to have multiple SetProp() without adding unnecessary SetCell() so chaining SetProp() from the first one was the least impactful._ ``` // Example of api change mapper.AddMappingProductRow>("colname", p => p.propname1); // curent api => Both // equal mapper.AddMappingProductRow>("colname", p => p.propname1, Enum.Both);

//  split responsibility mapper.AddMappingProductRow>("colname", p => p.propname2, Enum.SetPropOnly).SetPropertyUsing(blabla2...);
mapper.AddMappingProductRow>("colname", p => p.propname2, Enum.SetCellOnly).SetCellUsing(blabla3...);

// Imply necessity to enforce responsibility by (raise error ?, mute first keep last ?) => means more codebase impact

// Raise error because already defined ?
mapper.AddMappingProductRow>("colname", p => p.propname2, Enum.SetCellOnly).SetCellUsing(blabla3...);
mapper.AddMappingProductRow>("colname", p => p.propname2, Enum.SetCellOnly).SetCellUsing(blabla2...);

// Raise error because mismatch responsibility ?
mapper.AddMappingProductRow>("colname", p => p.propname2, Enum.SetCellOnly).SetPropertyUsing(blabla2...);
```
This is achievable ! It's just way more refacto

**Comment by hguy** [comment]
We could also specialise the `mapper.AddMapping<ProductRow>()` instead of using an "Enum.Direction".
something like 
```
mapper.AddMapping<ProductRow>("colname", p => p.propname2); // Both direction 

// Return a specialised ColumnInfo with a limited interface for this direction
mapper.AddMappingExcelToObject<ProductRow>("colname", p => p.propname2); // only SetPropertyUsing is available for chaining
mapper.AddMappingExcelToObject<ProductRow>("colname", p => p.propname3); // You can have multiple SepProp with the same "colname"

mapper.AddMappingObjectToExcel<ProductRow>(p => p.propname2, "colname"); // only SetCellUsing is available for chaining
mapper.AddMappingObjectToExcel<ProductRow>(p => p.propname3, "colname"); // Raise error "colname already have a setter"
```

**Comment by mganss** [comment]
I like the last approach, although IMO it doesn't even have to be this clever. We could just add fluent methods that set the direction and still return the full `ColumnInfo`. So

```c#
mapper.AddMapping(...).FromExcelOnly().SetPropertyUsing(...);
mapper.AddMapping(...).ToExcelOnly().SetCellUsing(...);

/// plus the corresponding attributes
[FromExcelOnly]
...

[ToExcelOnly]
...
```

If there's more than one `ColumnInfo` where `FromExcelOnly` is false then we'll just execute all cell setters 🤷

**Pull request closed without merging**
