### PR TITLE
Added an excel sheet with whitespaces and was unable to import the data

### PR DESCRIPTION
**Pull request by NdubuisiJr**
Apparently, the `else-if` check in the `SetProperty` method in `TypeMapper` class does not account for white spaces in an excel sheet.

### CODE REVIEW

**Comment by NdubuisiJr** [comment]
That is why the test failed...

**Comment by NdubuisiJr** [comment]
I would have reported this as an Issue but I wanted you to see the test

**Comment by mganss** [comment]
We should probably expand this check here: https://github.com/mganss/ExcelMapper/blob/d5da0e58133d4567a890d29153471700de3ebd50/ExcelMapper/ExcelMapper.cs#L299

This won't deal with blank cells that are in otherwise non-empty rows, though. Perhaps we should also skip blank cells in `SetProperty` if `SkipBlankRows` is true. But I think we should take care not to skip before the custom `SetProp` and if the property is a string.

**Comment by NdubuisiJr** [comment]
That's a pretty good Idea...
What I had in mind was to put an additional `else-if` [here](https://github.com/mganss/ExcelMapper/blob/d5da0e58133d4567a890d29153471700de3ebd50/ExcelMapper/TypeMapper.cs#L195) that will check if the cell contains whitespaces and then set `v` to the default value of `PropertyType`... 

something like this:
```
else if (val != null && string.IsNullOrWhiteSpace(val.ToString())
{
    v=GetDefault(val.GetType());
}
```

    ```
  private static object GetDefault(Type type)
        {
            if (type.IsValueType)
            {
                return Activator.CreateInstance(type);
            }
            return null;
        }  
```

**Comment by mganss** [comment]
I've changed my mind and just skipped all empty cells in `Fetch()` if `SkipBlankRows` is true.

**Pull request closed without merging**
