### PR TITLE
New Fetch methods and Refactoring of existing ones 

### PR DESCRIPTION
**Pull request by NdubuisiJr**
This library is a great one and it has helped make my work easier. I reckoned that its capabilities will be greatly increased if it could import data through a type passed in as a parameter. At first, this might appear unreasonable but if you consider a scenario where the developer does not actually know the headers or the column count in the excel file you'll probably get the picture :)

In this scenario, the developer can get the sheet names and headers using NPOI, create a `Type` dynamically and add the headers as properties to the `Type` but at the end He/She won't be able to read the data with this dynamically created type because we only have `Fetch<T>(...)`. This prompted the need for the new methods and the corresponding refactoring that followed suit.

Please review, I'll be expecting your feed back. Thanks

### CODE REVIEW

**Comment by mganss** [comment]
Thanks for the PR.

I think the overloads taking `Type` aren't strictly necessary because you can call the generic methods with a type known at runtime using reflection, see https://stackoverflow.com/a/232621/1970064

We don't need the custom exception, we can use plain old `ArgumentException`.

Can you add more tests to increase the coverage?
Will the .sln open without errors if the .editorconfig file is not there?

**Comment by NdubuisiJr** [comment]
Yes, It's not strictly necessary but it kinda saves the developer some extra brain storming and makes the methods a little more intuitive.

I've removed the custom exception and the associated tests.

I've added test cases to cover the new methods and the refactored ones.

The solution is going to open. The .editorconfig file just holds some vs2019 user defined settings.

**Comment by mganss** [comment]
@NdubuisiJr The unit tests fail. This may be because you're not closing the stream.

**Comment by NdubuisiJr** [comment]
Yeah... The thing is that, the test was trying to save the data to a file path (`"dataitemstracked.xlsx"`) that was used in  `ColumnTest()`.  If the test is run alone it passes. I've changed the filename to `"dataitemstracked1.xlsx"`...

**Pull request merged**
