### PR TITLE
Feature/fetch sheet names

### PR DESCRIPTION
**Pull request by BeyondMySouls**
I added a method to fetch sheet names, I find it useful in my application. You may check whether you find it useful for the repo.

**Some Use Cases:**
var sheetNames = excelMapper.FetchSheetNames();

Use Case 1. - When all sheets use the same Product template
```
foreach (var index in sheetNames.Keys)
{
    listProducts.Add(excel.Fetch<Product>(index));
}
```
Use Case 2. - Each sheet can be read into an object to process further
```
var tables = new List<Table>() { new Table { SheetName = "", Rows = null } };

foreach (var sheetName in sheetNames.Values)
{
    var rows = excel.Fetch<Product>(sheetName);
    tables.Add(new Table() { SheetName = sheetName, Rows = rows };);
}
```
Use Case 3. - You can exclude specific sheet names
```
foreach (var sheetName in sheetNames.Values)
{
    if (sheetName.In("Overview", "Examples", "Comments")
        continue;
    // else fetch
}
```

### CODE REVIEW

**Comment by mganss** [comment]
Thanks for the contribution. IMO the code is a little too verbose. Why not reuse the Workbook that we already have? Then it could be a one-liner:

```c#
public IEnumerable<string> GetSheetNames() => Workbook == null ? Array.Empty<string>()
    : Enumerable.Range(0, Workbook.NumberOfSheets).Select(i => Workbook.GetSheetName(i));
```

A dictionary is redundant if the keys are just the implicit indexes of the enumerable.

**Comment by BeyondMySouls** [comment]
Sure, I'll check it.

**Comment by albertbethlowsky** [comment]
Any chance this feature will be pushed to the master soon? :D

**Comment by mganss** [comment]
This is in 5.2.375.

**Pull request merged**
