### PR TITLE
Add support for byte[] PropertyType and ExpandoObject nullable properties

### PR DESCRIPTION
**Pull request by andywu188**

### CODE REVIEW

**Comment by mganss** [comment]
Thanks. Could you add unit tests as well?

**Comment by andywu188** [comment]
Yes, no problem.

**Comment by andywu188** [comment]
There are too many contents in the tests.cs file. It is recommended to split multiple test files as soon as possible and put xlsx into a separate folder at the same time. Otherwise, it looks a bit confusing

**Comment by mganss** [comment]
OK I've moved the xlsx files to a subfolder. Feel free to create a new file for your test code.

**Pull request closed without merging**
