### PR TITLE
Adds Table formatting to Save methods

### PR DESCRIPTION
**Pull request by SheepRock**
Adds an option to specify an Excel table style to apply to the data. Table styles are specified as the string name of the style (`"TableStyleMedium3"`, `"TableStyleLight7"`,`"TableStyleDark5"`). 

Data must be save in xlsx and have HeaderRow enabled.

image

### CODE REVIEW

**Comment by mganss** [comment]
Sorry for the late response. I'm hesitant to add another parameter to the `Save()` methods. I'd rather add an event that gets invoked just before the workbook is written. The table styling method could then become an extension method of `XSSFSheet`.

**Comment by SheepRock** [comment]
Will take a look. I was also think in using an enum instead of a string to the table style, what do you think? POI appears to have that enum, but it is absent in NPOI.

**Comment by mganss** [comment]
You can have custom table styles can't you? If so, perhaps the builtin styles can become const strings.

**Comment by mryanmurphy** [comment]
I adapted the code here into a Save event handler to setup tables for all sheets, it may be helpful for others finding this PR. Fixed a bug where tables didn't have globally unique ids. Instead there were unique ids per sheet, which excel considers corruption requiring repair.

https://gist.github.com/mryanmurphy/d9138cd69d4f7a2c8e253f93cb4770dd

**Pull request closed without merging**
